export enum TipoEstadoCompra {
    PENDIENTE = 'PENDIENTE',
    COMPLETADA = 'COMPLETADA',
    CANCELADA = 'CANCELADA',
    REEMBOLSADA = 'REEMBOLSADA',
    PARCIALMENTE_REEMBOLSADA = 'PARCIALMENTE_REEMBOLSADA'
}
